In [1]:
import pandas as pd
import numpy as np

## Testing reverse complement

In [9]:
A = np.array([1,0,0,0], dtype=np.float32)
C = np.array([0,1,0,0], dtype=np.float32)
G = np.array([0,0,1,0], dtype=np.float32)
T = np.array([0,0,0,1], dtype=np.float32)

seq_dict = {'A': A, 'C': C, 'G': G, 'T': T}
seq_dict

{'A': array([1., 0., 0., 0.], dtype=float32),
 'C': array([0., 1., 0., 0.], dtype=float32),
 'G': array([0., 0., 1., 0.], dtype=float32),
 'T': array([0., 0., 0., 1.], dtype=float32)}

In [ ]:
tuple(seq_dict[s] for s in seq)

In [ ]:
input_np = np.array([A, C, G, T])
input_np

In [27]:
def sequence_to_encoding(seq, encoding_dict):
    return(np.array(tuple(encoding_dict[s] for s in seq)))


def encoding_to_sequence(input_array, encoding_dict, delim_indices=None):

    import copy 

    keys = list(encoding_dict.keys())
    values = list(encoding_dict.values())
    values = [ar.tolist() for ar in values]

    if len(input_array.shape) != 2:
        raise Exception('Input array should have 2 dimensions')

    seq_list = []
    for i, na in enumerate(range(input_array.shape[0])):
        ts = input_array[i,:].tolist()
        # look up in the dictionary
        id = values.index(ts)
        seq_list.append(keys[id])

    if delim_indices is not None:
        seq = [seq_list[i] if i in delim_indices else seq_list[i].lower() for i in range(len(seq_list)) ] #
        return(''.join(seq))
    else:
        return(''.join(seq_list))

In [28]:
a = sequence_to_encoding('ACCGTAT', seq_dict)
a, a.shape

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]], dtype=float32),
 (7, 4))

In [30]:
b = encoding_to_sequence(a, seq_dict)
b, len(b)

('ACCGTAT', 7)

In [33]:
input_sequence = "GCTAAACT"
input_encoding = sequence_to_encoding(input_sequence, seq_dict)
input_sequence, input_encoding

('GCTAAACT',
 array([[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]], dtype=float32))

In [34]:
reversed = np.flip(input_encoding, axis=0)
reversed

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [36]:
encoding_to_sequence(reversed, seq_dict), input_sequence

('TCAAATCG', 'GCTAAACT')

In [42]:
encoding_to_sequence(np.flip(reversed, axis=1), seq_dict), input_sequence

('AGTTTAGC', 'GCTAAACT')

In [ ]:
np.flip(np.flip(input_encoding, axis=0), axis=1)

In [49]:
haplotypes = ['ACTGCGA', 'GTCGAGT']
samples = ['sam1', 'sam2']
hap_names = ['haplotype1', 'haplotype2']

encoding_dict = {}
for sam in samples:
    encoding_dict[sam] = {}
    for i, hap in enumerate(haplotypes):
        encoding_dict[sam][hap_names[i]] = sequence_to_encoding(hap, seq_dict)
print(encoding_dict)

{'sam1': {'haplotype1': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32), 'haplotype2': array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)}, 'sam2': {'haplotype1': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32), 'haplotype2': array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)}}


In [50]:
def reverse_complement_one_hot_encoded_sequences(one_hot_encoded_sequence):
    import numpy as np
    return(np.flip(np.flip(one_hot_encoded_sequence, axis=0), axis=1))

In [51]:
haplotypes_rcs = ['haplotype1_rc', 'haplotype2_rc']
for sample, haplotypes_encoded in encoding_dict.items():
    hapnames = list(haplotypes_encoded.keys())
    for i in range(len(hapnames)):
        encoding_dict[sample][haplotypes_rcs[i]] = reverse_complement_one_hot_encoded_sequences(encoding_dict[sample][hapnames[i]])
encoding_dict

{'sam1': {'haplotype1': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.]], dtype=float32),
  'haplotype2': array([[0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]], dtype=float32),
  'haplotype1_rc': array([[0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]], dtype=float32),
  'haplotype2_rc': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.]], dtype=float32)},
 'sam2': {'haplotype1': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
  

In [53]:
haplotypes = ['ACTGCGA', 'GTCGAGT']
hap_names = ['haplotype1', 'haplotype2']

ref_encoding_dict = {}
ref_encoding_dict['sequence'] = {}
for i, hap in enumerate(haplotypes):
    ref_encoding_dict['sequence'][hap_names[i]] = sequence_to_encoding(haplotypes[i], seq_dict)
print(ref_encoding_dict)

{'sequence': {'haplotype1': array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32), 'haplotype2': array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)}}


In [54]:
haplotypes_rcs = ['haplotype1_rc', 'haplotype2_rc']
hapnames = list(ref_encoding_dict['sequence'].keys())
for i in range(len(hapnames)):
    ref_encoding_dict['sequence'][haplotypes_rcs[i]] = reverse_complement_one_hot_encoded_sequences(ref_encoding_dict['sequence'][hapnames[i]])
ref_encoding_dict

{'sequence': {'haplotype1': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.]], dtype=float32),
  'haplotype2': array([[0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]], dtype=float32),
  'haplotype1_rc': array([[0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]], dtype=float32),
  'haplotype2_rc': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.]], dtype=float32)}}

In [6]:
logfile = '/lus/grand/projects/covid-ct/imlab/users/temi/projects/TFXcan/TFPred_pipeline/prediction_folder/predictions_log/geuvadis_AR/predictions_log_2023-01-27.csv'
logfile = pd.read_csv(logfile)
logfile.head(), logfile.shape

(                       motif individual     status sequence_type
 0  chr12_119667745_119668095    HG00096  completed           var
 1  chr12_109940195_109940745    HG00096  completed           var
 2  chr12_110048445_110048895    HG00096  completed           var
 3  chr12_119716295_119717145    HG00096  completed           var
 4  chr12_117038095_117039145    HG00096  completed           var,
 (616254, 4))

In [7]:
sample = 'HG00128'
id_logfile = logfile.loc[logfile['individual'] == sample, : ]
id_logfile.head(), id_logfile.shape

(                            motif individual     status sequence_type
 548969    chr10_98332743_98333443    HG00128  completed           var
 548970    chr10_98414943_98415443    HG00128  completed           var
 548971    chr10_99945143_99945843    HG00128  completed           var
 548972    chr10_98470843_98471293    HG00128  completed           var
 548973  chr10_100185843_100186293    HG00128  completed           var,
 (18654, 4))

In [23]:
queries = pd.read_table('/lus/grand/projects/covid-ct/imlab/users/temi/projects/TFXcan/baca_cwas/predictors/baca_cwas_AR_regions_hg38_2023-01-27.txt', header=None).dropna(axis=0)[0].tolist()[0:10000]
queries

['chr1_99543994_99544394',
 'chr1_9943142_9943692',
 'chr1_99598344_99598844',
 'chr1_99615044_99615644',
 'chr1_99766294_99766944',
 'chr1_99806744_99807394',
 'chr1_99836194_99836794',
 'chr1_100037994_100038294',
 'chr1_100132694_100133394',
 'chr1_100202594_100203294',
 'chr1_100239894_100240544',
 'chr1_100351494_100351894',
 'chr1_100352294_100352644',
 'chr1_100414694_100415194',
 'chr1_100419294_100419794',
 'chr1_100452544_100453344',
 'chr1_10032592_10033142',
 'chr1_1074020_1074370',
 'chr1_100874244_100874944',
 'chr1_100875044_100875644',
 'chr1_100916494_100917144',
 'chr1_100930944_100931244',
 'chr1_100946944_100947594',
 'chr1_101288494_101288994',
 'chr1_10210292_10210542',
 'chr1_10430293_10430793',
 'chr1_104630728_104631178',
 'chr1_104884128_104884728',
 'chr1_104953428_104954328',
 'chr1_105394878_105395428',
 'chr1_105395878_105396528',
 'chr1_105399778_105400578',
 'chr1_105533278_105533678',
 'chr1_105572678_105573328',
 'chr1_106134478_106135078',
 'chr1_1062

In [24]:
output_dir = '/lus/grand/projects/covid-ct/imlab/users/temi/projects/TFXcan/TFPred_pipeline/prediction_folder/enformer_predictions/geuvadis_AR/predictions_2023-01-27'

In [25]:
def check_queries(sample, queries, output_dir, logfile):
    """
    Check whether a given region, for an individual has been predicted and logged.

    Parameters:
        sample: str 
            The name/id of an individual
        queries: A batch
            A region in the genome in the form `chr_start_end`.
        output_dir: str (path)
            The folder where the predictions should have been logged. 
        logfile: pd.DataFrame 
            A dataframe of a log file or `None` if the log file does not exist. 
    
    Returns: dict
        'query': the query region if it has not been logged or predictions don't exist
        'logtype': whether it should be logged if it has not been logged

    If predictions exist and the query has been logged, this function returns None.
    """
    import pandas as pd
    import os
    import numpy as np

    if isinstance(logfile, type(None)):
        output = [{'query':query, 'logtype':'y'} for query in queries]
        return(output)

    elif isinstance(logfile, pd.DataFrame):# should have read it>

        id_logfile = logfile.loc[logfile['individual'] == sample, : ]

        # check if the file is saved
        queries_saved = [str(f'{output_dir}/{sample}/{query}_predictions.h5') for query in queries]
        queries_saved = np.array([os.path.isfile(q) for q in queries_saved])

        # check if the file is in the logfile
        query_logged = np.array([(query in id_logfile.motif.values) for query in queries])

        # 
        assert query_logged.shape[0] == queries_saved.shape[0], "Lengths of queries logged and saved conditions are not the same"
        queries_condition = queries_saved * query_logged
        queries_condition = queries_condition.tolist()

        # 
        output = [{'query':queries[i], 'logtype':'n'} if qc is True else {'query':queries[i], 'logtype':'y'} for i, qc in enumerate(queries_condition)]

        return(output)


In [26]:
check_query(sample, queries, output_dir, logfile)

[{'query': 'chr1_99543994_99544394', 'logtype': 'n'},
 {'query': 'chr1_9943142_9943692', 'logtype': 'n'},
 {'query': 'chr1_99598344_99598844', 'logtype': 'n'},
 {'query': 'chr1_99615044_99615644', 'logtype': 'n'},
 {'query': 'chr1_99766294_99766944', 'logtype': 'n'},
 {'query': 'chr1_99806744_99807394', 'logtype': 'n'},
 {'query': 'chr1_99836194_99836794', 'logtype': 'n'},
 {'query': 'chr1_100037994_100038294', 'logtype': 'n'},
 {'query': 'chr1_100132694_100133394', 'logtype': 'n'},
 {'query': 'chr1_100202594_100203294', 'logtype': 'n'},
 {'query': 'chr1_100239894_100240544', 'logtype': 'n'},
 {'query': 'chr1_100351494_100351894', 'logtype': 'n'},
 {'query': 'chr1_100352294_100352644', 'logtype': 'n'},
 {'query': 'chr1_100414694_100415194', 'logtype': 'n'},
 {'query': 'chr1_100419294_100419794', 'logtype': 'n'},
 {'query': 'chr1_100452544_100453344', 'logtype': 'n'},
 {'query': 'chr1_10032592_10033142', 'logtype': 'n'},
 {'query': 'chr1_1074020_1074370', 'logtype': 'n'},
 {'query': 'ch

In [14]:
os.path.isfile(f'{output_dir}/{sample}/chr10_98332743_98333443_predictions.h5')

True

In [17]:
np.array([True, False, True])

(3,)

In [27]:
def generate_batch(lst, batch_n, len_lst = None):
    """
    Given a list, this function yields batches of an unspecified size but the number of batches is equal to `batch_n`
    E.g. generate_batch([0, 1, 2, 3, 4, 5, 6], batch_n=2) -> (0, 1, 2, 3), (4, 5, 6)
    
    Parameters:
        lst: list
        batch_n: int
            Number of batches to return
        len_lst: None or num (length of the input list)

    Yields
        `batch_n` batches of the list
    """
    import math
    # how many per batch
    if len_lst is not None:
        n_elems = math.ceil(len_lst/batch_n)
    else:
        n_elems = math.ceil(len(lst)/batch_n)
        
    for i in range(0, len(lst), n_elems):
        yield lst[i:(i + n_elems)]

In [37]:
chromosomes = [f'chr{i}' for i in range(1, 23)]
chromosomes.extend(['chrX'])
chromosomes

['chr1',
 'chr2',
 'chr3',
 'chr4',
 'chr5',
 'chr6',
 'chr7',
 'chr8',
 'chr9',
 'chr10',
 'chr11',
 'chr12',
 'chr13',
 'chr14',
 'chr15',
 'chr16',
 'chr17',
 'chr18',
 'chr19',
 'chr20',
 'chr21',
 'chr22',
 'chrX']

In [47]:
batch_list = []
for chromosome in chromosomes:
    # print(chromosome)
    # print(list_of_regions[0:5])
    chr_list_of_regions = [r for r in queries if r.startswith(f"{chromosome}_")]
    a = list(generate_batch(id_logfile.motif.tolist(), 40))
    batch_list.append(a)

In [48]:
len(a)

40

In [49]:
for i in a:
    print(len(i))

467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
467
441


In [50]:
len(queries)

10000